services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: 5513479285:AAG4SGngQcnQycQYBkj59noDkgSSYDOLOyA
        sync: false
      - key: PORT
        value: 8080